// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KogiStateUniSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void kSUWrongusernamepassword() {
    driver.get("https://portal.ksu.edu.ng/Login");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.id("username")).sendKeys("K79624");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.cssSelector(".field-validation-error")).click();
    assertThat(driver.findElement(By.cssSelector(".field-validation-error")).getText(), is("Invalid Username or Password"));
    driver.close();
  }
  @Test
  public void kSUValidusernamewrongpassword() {
    driver.get("https://portal.ksu.edu.ng/Login");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ryte2chart@yahoo.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.cssSelector(".field-validation-error")).click();
    driver.findElement(By.cssSelector(".field-validation-error")).click();
    assertThat(driver.findElement(By.cssSelector(".field-validation-error")).getText(), is("Invalid Username or Password"));
    driver.close();
  }
}
